version: '3.3'

services:
    nginx:
        image: nginx:alpine
        restart: always
        # Ensyre renewed certificates are reloaded
        command: /bin/sh -c \
                     'while :; do
                         sleep 6h & wait $${!};
                         nginx -s reload;
                      done & nginx -g "daemon off;"'
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./certbot/www:/var/www/certbot
            - ./certbot/files:/etc/letsencrypt
            - ./social:/var/www/social
    certbot:
        image: certbot/certbot
        # Check for certificate renewal every 12h as
        # recomnended by Let's Encryot
        entrypoint: /bin/sh -c \
                        'trap exit TERM;
                         while :; do
                             certbot renew > /dev/null;
                             sleep 12h & wait $${!};
                         done'
        volumes:
            - ./certbot/www:/var/www/certbot
            - ./certbot/files:/etc/letsencrypt

