version: '3.3'

services:
    nginx:
        image: nginx:alpine
        restart: always
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
            - ./certbot/www:/var/www/certbot
            - ./certbot/files:/etc/letsencrypt
            - ./social:/var/www/social
    certbot:
        image: certbot/certbot
        volumes:
            - ./certbot/www:/var/www/certbot
            - ./certbot/files:/etc/letsencrypt

