version: '3.4'

services:
  nginx:
    image: nginx:alpine
    depends_on:
      - php
    restart: always
    # Suppress nginx noise
    tty: false
    # Ensyre renewed certificates are reloaded
    command: /bin/sh -c \
           'while :; do
             sleep 6h & wait $${!};
             nginx -s reload;
           done & nginx -g "daemon off;"'
    ports:
      - 80:80
      - 443:443
    volumes:
      # General nginx
      - ./docker/nginx/ssl-common.conf:/etc/nginx/include.d/ssl-common.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      # Landing page
      - ./docker/nginx/landing.conf:/etc/nginx/conf.d/landing.conf
      - ./docker/nginx/landing.html:/etc/nginx/html/landing.html
      # Certbot
      - ./docker/certbot/www:/var/www/certbot
      - ./docker/certbot/files:/etc/letsencrypt
      # GNU social
      - ./docker/social/social.conf:/etc/nginx/conf.d/social.conf
      - ./social/public:/var/www/social/public
      # GNU FM
      - ./docker/fm/gnufm.conf:/etc/nginx/conf.d/gnufm.conf
      - ./fm/gnukebox:/var/www/gnukebox
      - ./fm/nixtape:/var/www/nixtape
      # Keycloak
      - ./docker/keycloak/keycloak.conf:/etc/nginx/conf.d/keycloak.conf
    # logging:
    #   driver: "none"

  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    # Check for certificate renewal every 12h as
    # recomnended by Let's Encryot
    entrypoint: /bin/sh -c \
            'trap exit TERM;
             while :; do
               certbot renew > /dev/null;
               sleep 12h & wait $${!};
             done'
    volumes:
      - ./docker/certbot/www:/var/www/certbot
      - ./docker/certbot/files:/etc/letsencrypt

  php:
    depends_on:
      - db
      # - keycloak
    build: ./docker/php
    restart: always
    tty: true
    ports:
      - 9000:9000
    volumes:
      # Config
      - ./docker/php/php.ini:/etc/php/php.ini
      - ./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      # Entrypoint
      - ./docker/php/entrypoint.sh:/entrypoint.sh
      - ./docker/db/wait_for_db.sh:/wait_for_db.sh
      # GNU social
      - ./social:/var/www/social
      - ./docker/social/install.sh:/var/entrypoint.d/social_install.sh
      # GNU FM
      - ./fm/gnukebox:/var/www/gnukebox
      - ./fm/nixtape:/var/www/nixtape
      - ./docker/fm/gnukebox.sh:/var/entrypoint.d/gnukebox.sh
      - ./docker/fm/nixtape.sh:/var/entrypoint.d/nixtape.sh
      - ./docker/fm/install_gnukebox.php:/var/install/gnukebox.php
      - ./docker/fm/install_nixtape.php:/var/install/nixtape.php
    env_file:
      - ./docker/db/db.env
      - ./docker/social/social.env
      - ./docker/fm/fm.env
    command: /entrypoint.sh

  db:
    image: mariadb
    env_file:
      - ./docker/db/db.env
      - ./docker/social/social.env
      - ./docker/fm/fm.env
      - ./docker/keycloak/keycloak.env
    volumes:
      # Configuration
      - ./docker/db/my.cnf:/etc/mysql/my.cnf
      - ./docker/db/mariadb.cnf:/etc/mysql/mariadb.cnf
      # GNU social
      - ./docker/db/social.sh:/docker-entrypoint-initdb.d/social.sh
      # GNU FM
      - ./docker/db/fm.sh:/docker-entrypoint-initdb.d/fm.sh
      # Keycloak
      - ./docker/db/keycloak.sh:/docker-entrypoint-initdb.d/keycloak.sh
    ports:
      - 3306:3306

  keycloak:
    build: ./docker/keycloak
    env_file: ./docker/keycloak/keycloak.env
    ports:
      - 8080:8080
    volumes:
      - ./docker/keycloak/mysqladmin.sh:/install.sh
      - ./docker/db/wait_for_db.sh:/wait_for_db.sh

  smtp:
    build: ./docker/smtp
    restart: always
    ports:
     - 25:25
     - 465:465
     - 587:587
    environment:
      - MAILNAME=mail.hsales.me
    volumes:
      - ./docker/certbot/files/:/etc/certs/
      - ./docker/certbot/files/live/hsales.me/fullchain.pen:/etc/x509/https/tls.key
      - ./docker/certbot/files/live/hsales.me/cert.pen:/etc/x509/https/tls.crt


