version: '3.4'

services:
  nginx:
    build: ./docker/nginx
    depends_on:
      - php
    restart: always
    # Suppress nginx noise
    tty: false
    # Ensyre renewed certificates are reloaded
    command: /bin/sh -c \
           'while :; do
             sleep 6h & wait $${!};
             /usr/local/openresty/bin/openresty -s reload;
           done & /usr/local/openresty/bin/openresty -g "daemon off;"'
    ports:
      - 80:80
      - 443:443
    volumes:
      # General nginx
      - ./docker/nginx/ssl-common.conf:/usr/local/openresty/nginx/conf/include.d/ssl-common.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      # Landing page
      - ./docker/nginx/landing.conf:/etc/nginx/conf.d/landing.conf
      - ./docker/nginx/landing.html:/usr/local/openresty/nginx/html/landing.html
      # Certbot
      - ./docker/certbot/www:/var/www/certbot
      - ./docker/certbot/files:/etc/letsencrypt
      # GNU social
      - ./docker/social/social.conf:/etc/nginx/conf.d/social.conf
      - ./social/public:/var/www/social/public
      # GNU FM
      - ./docker/fm/gnufm.conf:/etc/nginx/conf.d/gnufm.conf
      - ./fm/gnukebox:/var/www/gnukebox
      - ./fm/nixtape:/var/www/nixtape
      # Keycloak
      - ./docker/keycloak/keycloak.conf:/etc/nginx/conf.d/keycloak.conf
    # logging:
    #   driver: "none"

  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    # Check for certificate renewal every 12h as
    # recomnended by Let's Encryot
    entrypoint: /bin/sh -c \
            'trap exit TERM;
             while :; do
               certbot renew > /dev/null;
               sleep 12h & wait $${!};
             done'
    volumes:
      - ./docker/certbot/www:/var/www/certbot
      - ./docker/certbot/files:/etc/letsencrypt

  php:
    depends_on:
      - db
    build: ./docker/php
    restart: always
    tty: true
    ports:
      - 9000:9000
    volumes:
      # Entrypoint
      - ./docker/php/entrypoint.sh:/entrypoint.sh
      - ./docker/mariadb/wait_for_db.sh:/wait_for_db.sh
      # GNU social
      - ./social:/var/www/social
      - ./docker/social/install.sh:/var/entrypoint.d/social_install.sh
      # GNU FM
      - ./fm/gnukebox:/var/www/gnukebox
      - ./fm/nixtape:/var/www/nixtape
      - ./docker/fm/gnukebox.sh:/var/entrypoint.d/gnukebox.sh
      - ./docker/fm/nixtape.sh:/var/entrypoint.d/nixtape.sh
      - ./docker/fm/install_gnukebox.php:/var/install/gnukebox.php
      - ./docker/fm/install_nixtape.php:/var/install/nixtape.php
    env_file:
      - ./docker/mariadb/mariadb.env
      - ./docker/social/social.env
      - ./docker/fm/fm.env
    command: /entrypoint.sh

  db:
    image: mariadb
    env_file:
      - ./docker/mariadb/mariadb.env
      - ./docker/social/social.env
      - ./docker/fm/fm.env
      - ./docker/keycloak/keycloak.env
    volumes:
      # Configuration
      - ./docker/mariadb/my.cnf:/etc/mysql/my.cnf
      - ./docker/mariadb/mariadb.cnf:/etc/mysql/mariadb.cnf
      # GNU social
      - ./docker/mariadb/social.sh:/docker-entrypoint-initdb.d/social.sh
      # GNU FM
      - ./docker/mariadb/fm.sh:/docker-entrypoint-initdb.d/fm.sh
      # Keycloak
      - ./docker/mariadb/keycloak.sh:/docker-entrypoint-initdb.d/keyclok.sh
    ports:
      - 3306:3306
    logging:
      driver: "none"


